config/routes.rb
Rails.application.routes.draw do
    resources :rental_records

  resources :rentals do
    collection do 
      get 'home'
    end
  end
  resources :devices
  
  root :to => 'devices#home'

end

app/models/rental_record.rb
class RentalRecord < ActiveRecord::Base
  #attr_accessible :device_id, :email, :end, :renter, :total_time
  belongs_to :device
end

app/controllers/rental_records_controller.rb
class RentalRecordsController < ApplicationController
  # GET /rental_records
  # GET /rental_records.json
  def index
    @rental_records = RentalRecord.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @rental_records }
    end
  end

  # GET /rental_records/1
  # GET /rental_records/1.json
  def show
    @rental_record = RentalRecord.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @rental_record }
    end
  end

  # GET /rental_records/new
  # GET /rental_records/new.json
  def new
    @rental_record = RentalRecord.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @rental_record }
    end
  end

  # GET /rental_records/1/edit
  def edit
    @rental_record = RentalRecord.find(params[:id])
  end

  # POST /rental_records
  # POST /rental_records.json
  def create
    @rental_record = RentalRecord.new(params[:rental_record])

    respond_to do |format|
      if @rental_record.save
        format.html { redirect_to @rental_record, notice: 'Rental record was successfully created.' }
        format.json { render json: @rental_record, status: :created, location: @rental_record }
      else
        format.html { render action: "new" }
        format.json { render json: @rental_record.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /rental_records/1
  # PUT /rental_records/1.json
  def update
    @rental_record = RentalRecord.find(params[:id])

    respond_to do |format|
      if @rental_record.update_attributes(params[:rental_record])
        format.html { redirect_to @rental_record, notice: 'Rental record was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @rental_record.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rental_records/1
  # DELETE /rental_records/1.json
  def destroy
    @rental_record = RentalRecord.find(params[:id])
    @rental_record.destroy

    respond_to do |format|
      format.html { redirect_to rental_records_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/rental_records_helper.rb
module RentalRecordsHelper
end

app/views/rental_records/_form.html.erb
<%= form_for(@rental_record) do |f| %>
  <% if @rental_record.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@rental_record.errors.count, "error") %> prohibited this rental_record from being saved:</h2>

      <ul>
      <% @rental_record.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :email %><br />
    <%= f.text_field :email, :class => 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :renter %><br />
    <%= f.text_field :renter, :class => 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :comments %><br />
    <%= f.text_field :comment, :class => 'form-control' %>
  </div>  
  <div class="form-group">
    <%= f.label :end %><br />
    <%= f.date_select :end %>
  </div>
  <div class="form-group">
    <%= f.label :device_id %><br />
    <%= collection_select(:device, :device_id, Device.all, :id, :device_id) %>
  </div>
  <div class="form-group">
    <%= f.label :total_time %> (days)<br />
    <%= f.number_field :total_time %>
  </div>
  <div class="form-group">
    <%= f.label :rate_daily %><br />
    <%= f.text_field :rate_daily, :class => 'form-control' %>
  </div>  
  <div class="form-group">
    <%= f.label :total_price %><br />
    <%= f.text_field :total_price, :class => 'form-control' %>
  </div>  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/rental_records/edit.html.erb
<h1>Editing rental_record</h1>

<%= render 'form' %>

<%= link_to 'Show', @rental_record %> |
<%= link_to 'Back', rental_records_path %>

app/views/rental_records/index.html.erb
<h1>Listing Records</h1>

<table class="table table-condensed">
  <tr>
    <th>Renter</th>
    <th>Returned</th>
    <th>Device</th>
    <th>Days</th>
    <th>Rate</th>
    <th>Total</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @rental_records.each do |rental_record| %>
  <tr>
    <td><%= rental_record.renter %> (<%= rental_record.email %>)</td>
    <td><%= rental_record.end %></td>
    <td><%= rental_record.device.device_id %> (<%= rental_record.device.device_type %>)</td>
    <td><%= rental_record.total_time %></td>
    <td><%= number_to_currency(rental_record.rate_daily) %></td>
    <td><%= number_to_currency(rental_record.total_price) %></td>
    <td><%= link_to 'Show', rental_record, :class => 'btn btn-primary' %></td>
    <td><%= link_to 'Edit', edit_rental_record_path(rental_record), :class => 'btn btn-default' %></td>
    <td><%= link_to 'Destroy', rental_record, method: :delete, data: { confirm: 'Are you sure?' }, :class => 'btn btn-inverse' %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Rental record', new_rental_record_path %>

app/views/rental_records/new.html.erb
<h1>New rental_record</h1>

<%= render 'form' %>

<%= link_to 'Back', rental_records_path %>

app/views/rental_records/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Email:</b>
  <%= @rental_record.email %>
</p>

<p>
  <b>Renter:</b>
  <%= @rental_record.renter %>
</p>

<p>
  <b>End:</b>
  <%= @rental_record.end %>
</p>

<p>
  <b>Device:</b>
  <%= @rental_record.device_id %>
</p>

<p>
  <b>Total time:</b>
  <%= @rental_record.total_time %>
</p>


<%= link_to 'Edit', edit_rental_record_path(@rental_record) %> |
<%= link_to 'Back', rental_records_path %>