config/routes.rb
Rails.application.routes.draw do
    resources :rental_records

  resources :rentals do
    collection do 
      get 'home'
    end
  end
  resources :devices
  
  root :to => 'devices#home'

end

app/models/device.rb
class Device < ActiveRecord::Base
  validates :device_id, :uniqueness => true
  #attr_accessible :device_id, :device_type, :additional_information
  validates_presence_of :device_id, :device_type
  has_one :rental
  scope :rented, -> { includes(:rental).where.not(:rentals => {:id => nil}) }
end

app/controllers/devices_controller.rb
class DevicesController < ApplicationController
  # GET /devices
  # GET /devices.json
  def index
    if params[:rented].present?
      @devices = Device.rented
    else
      @devices = Device.all
    end
    
    flash[:notice] = params[:notice]
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @devices }
    end
  end

  # GET /devices/1
  # GET /devices/1.json
  def show
    @device = Device.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @device }
    end
  end

  # GET /devices/new
  # GET /devices/new.json
  def new
    @device = Device.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @device }
    end
  end

  # GET /devices/1/edit
  def edit
    @device = Device.find(params[:id])
  end

  # POST /devices
  # POST /devices.json
  def create
    @device = Device.new(device_params)

    respond_to do |format|
      if @device.save
        format.html { redirect_to @device, notice: 'Device was successfully created.' }
        format.json { render json: @device, status: :created, location: @device }
      else
        format.html { render action: "new" }
        format.json { render json: @device.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /devices/1
  # PUT /devices/1.json
  def update
    @device = Device.find(params[:id])

    respond_to do |format|
      if @device.update_attributes(device_params)
        format.html { redirect_to @device, notice: 'Device was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @device.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /devices/1
  # DELETE /devices/1.json
  def destroy
    @device = Device.find(params[:id])
    @device.destroy

    respond_to do |format|
      format.html { redirect_to devices_url }
      format.json { head :no_content }
    end
  end

  private
  def device_params
    params.require(:device).permit(:device_id, :device_type, :rate_daily, :additional_information)
  end
end

app/helpers/devices_helper.rb
module DevicesHelper
end

app/views/devices/_form.html.erb
<%= form_for(@device) do |f| %>
  <% if @device.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@device.errors.count, "error") %> prohibited this device from being saved:</h2>
      <ul>
      <% @device.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :device_id %><br />
    <%= f.text_field :device_id, :class => 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :device_type %><br />
    <%= f.text_field :device_type, :class => 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :rate_daily %><br />
    <%= f.text_field :rate_daily, :class => 'form-control' %>
  </div>
    <div class="form-group">
    <%= f.label :additional_information %><br />
    <%= f.text_field :additional_information, :class => 'form-control'%>
  </div>
  <div class="actions">
    <%= f.submit "Submit", :class => "btn btn-primary" %>
  </div>
<% end %>

app/views/devices/edit.html.erb
<h1>Editing device</h1>

<%= render 'form' %>

<%= link_to 'Show', @device %> |
<%= link_to 'Back', devices_path %>

app/views/devices/home.html.erb
<div class="container">
	<div class="row">
		<div class="col-md-12">
			<div class="jumbotron">
				<h1>IDEO Device Rental</h1>
				<p>What would you like to do?</p>
				<a class="btn btn-large btn-default" href="/devices?rented=true">Return a device</a>
				<a class="btn btn-primary btn-large" href="/devices">Find a device</a>
			</div>
		</div>
 	</div>
</div>

app/views/devices/index.html.erb
<div class='container'>
  <div class='row'>
  <h1>Devices</h1>
    <% if flash[:notice] -%>
      <p class='notice'><%=h flash[:notice] %></p>
    <% end -%>
  <table class="table table-condensed table-striped">
    <tr>
      <th>Device</th>
      <th>Device type</th>
      <th>Notes</th>
      <th>Daily Rate</th>
      <th>Rented to</th>
      <th>Available After</th>
      <th>Actions</th>

    </tr>

  <% @devices.each do |device| %>
    <tr>
      <td><%= device.device_id %></td>
      <td><%= device.device_type %></td>
      <td><%= device.additional_information %></td>
      <td><%= number_to_currency(device.rate_daily) %></td>
      <% latest_rental = device.rental %>
      <% rental_empty = device.rental.nil? %>
      <td><%= (rental_empty ? "n/a": (mail_to latest_rental.email)) %></td>
      <td><%= (rental_empty ? "Currently Available": latest_rental.end) %> </td>
      <td>
      <% if(rental_empty) %>
        <%= link_to 'Rent', {:controller => "rentals", :action => "new", :device_id => device.id}, :class => "btn btn-sm btn-success" %>
      <% else %>
          <a class="btn btn-default" role="button" data-toggle="modal" href="#<%= device.device_id %>Modal"> Return </a>
          <div class="modal fade" id="<%= device.device_id %>Modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" style="display:none" aria-hidden="true">
            <div class="modal-dialog">
              <div class="modal-content">
                <div class="modal-header">
                  <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                  <h3 id="myModalLabel">Confirm Return</h3>
                </div>
                <div class="modal-body">
                  <p>Press Return Device if you have already returned the <%= device.device_type %> and all its accessories.</p>
                </div>
                <div class="modal-footer">
                  <button class="btn" data-dismiss="modal" aria-hidden="true">Close</button>
                  <%= link_to 'Return Device', latest_rental, method: :delete, :class => "btn btn-success btn-small", :id => device.device_id %>
                </div>
              </div>
            </div>
          </div>
      <% end %>
      </td>
    </tr>
  <% end %>
  </table>
  <br />
  <script type="text/javascript">
  //<![CDATA[
    $("a.checkReturn").on('click', function(e){
      var CODE = "<%= ENV['RETURN_CODE'] %>";
      fname = $("#" + $(this).attr("id") + "return").val();
      if(CODE != fname){
        e.preventDefault();
        e.stopPropagation();
        alert("Incorrect code given - please check the code posted in the D-Shop")
      }
    })
  //]]>
  </script>
</div>
</div>

app/views/devices/new.html.erb
<div class="container">
	<div class="row">
		<div class="col-md-3">
			<h1>New device</h1>
			<%= render 'form' %>
			<%= link_to 'Back', devices_path, :class => 'btn btn-default' %>
		</div>
	</div>
</div>

app/views/devices/show.html.erb
<div class="container">
	<div class="row">
		<div class="col-md-12">
			<p id="notice"><%= notice %></p>

			<p>
			  <b>Device:</b>
			  <%= @device.device_id %>
			</p>

			<p>
			  <b>Device type:</b>
			  <%= @device.device_type %>
			</p>
			<%= link_to 'Edit', edit_device_path(@device), :class => 'btn btn-primary' %>
			<%= link_to 'Back', devices_path, :class => 'btn btn-default' %>
		</div>
	</div>
</div>