config/routes.rb
Rails.application.routes.draw do
    resources :rental_records

  resources :rentals do
    collection do 
      get 'home'
    end
  end
  resources :devices
  
  root :to => 'devices#home'

end

app/models/rental.rb
class Rental < ActiveRecord::Base
  validates :device_id, :uniqueness => true
  validates_associated :device
  validates_presence_of :device_id, :email, :end, :renter, :device
  belongs_to :device
  after_initialize :defaults

  def self.emailRenters
    for renter in self.all
    	if renter.end < Date.current()
     		RenterMailer.reminderEmail(renter).deliver
     	end
    end
  end

  def defaults
    # Default rental to one week from now
    self.end = DateTime.now.to_date + 7
  end
end

app/controllers/rentals_controller.rb
class RentalsController < ApplicationController
  # GET /rentals
  # GET /rentals.json
  def index
    @rentals = Rental.all
   
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @rentals }
    end
  end

  # GET /rentals/1
  # GET /rentals/1.json
  def show
    @rental = Rental.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @rental }
    end
  end

  # GET /rentals/new
  # GET /rentals/new.json
  def new
    @rental = Rental.new
    @rental_id = params[:rental_id]
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @rental }
    end
  end

  # GET /rentals/1/edit
  def edit
    @rental = Rental.find(params[:id])
  end

  # POST /rentals
  # POST /rentals.json
  def create
    @rental = Rental.new(rental_params)
    @rental.end = Date.strptime(params[:end], "%m/%d/%Y")
    @rental.rate_daily = @rental.device.rate_daily

    respond_to do |format|
      if @rental.save
        RenterMailer.confirmEmail(@rental).deliver
        Rental.emailRenters
        format.html { redirect_to @rental, notice: "Thanks - you're all set!" }
        format.json { render json: @rental, status: :created, location: @rental }
      else
        format.html { render action: "new" }
        format.json { render json: @rental.errors, status: :unprocessable_entity }
      end
    end
  end
  # PUT /rentals/1
  # PUT /rentals/1.json
  def update
    @rental = Rental.find(params[:id])

    respond_to do |format|
      if @rental.update_attributes(params[:rental])
        format.html { redirect_to @rental, notice: 'Rental was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @rental.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rentals/1
  # DELETE /rentals/1.json
  def destroy
    @rental = Rental.find(params[:id])
    totalDays = (DateTime.now.to_date - @rental.created_at.to_date).to_i
    totalPrice = totalDays * @rental.rate_daily
    RentalRecord.create(
      :email => @rental.email,
      :renter => @rental.renter,
      :device_id => @rental.device_id,
      :total_time => totalDays,
      :rate_daily => @rental.rate_daily,
      :total_price => totalPrice,
      :end => @rental.end
      )
    @rental.destroy

    respond_to do |format|
      format.html { redirect_to :controller => "devices", :action => "index", notice: 'Return successful - Thanks!' }
      format.json { head :no_content }
    end
  end

  # GET /rentals/home
  def home

  end

  private
  def rental_params
      #attr_accessible :device_id, :email, :end, :renter, :comment
    params.require(:rental).permit(:device_id, :email, :end, :renter, :project, :comment)
  end
end

app/helpers/rentals_helper.rb
module RentalsHelper
end

app/views/rentals/_form.html.erb
<%= form_for(@rental) do |f| %>
  <% if @rental.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@rental.errors.count, "error") %> prohibited this rental from being saved:</h2>

      <ul>
      <% @rental.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="form-group">
    <%= f.label :name %><br />
    <%= f.text_field :renter, :class => 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :email %><br />
    <%= f.text_field :email, :class => 'form-control' %>
  </div>
    <div class="form-group">
    <%= f.label :project %><br />
    <%= f.text_field :project, :class => 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :notes %> Anything we should know about your use of this?<br />
    <%= f.text_field :comment, :class => 'form-control' %>
  </div>  
  <div class="form-group">
    <%= f.label :end %><br />

    <div class='input-group date' id='datetimepicker1'>
      <%= text_field_tag :end, nil, class: 'form-control', data: { date_format: 'MM/DD/YYYY' } %>
      <span class="input-group-addon"><span class="glyphicon glyphicon-calendar"></span></span>
    </div>
  </div>
  <script type="text/javascript">
        $(function () {
            $('#datetimepicker1').datetimepicker({
              defaultDate: moment("<%= @rental.end.strftime('%m/%d/%Y') %>"),
              format: "MM/DD/YYYY"
            });
        });
    </script>

  <%= f.hidden_field :device_id, :value => params[:device_id], :class => 'form-control' %>
  
  <div class="actions">
    <%= f.submit "Add rental", :class => "btn btn-primary" %>
  </div>
<% end %>

app/views/rentals/_returnForm.html.erb
<%= form_for(@rental) do |f| %>
  <% if @rental.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@rental.errors.count, "error") %> prohibited this return from being confirmed:</h2>

      <ul>
      <% @rental.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="form-group">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="form-group">
    <%= f.label :device_id %><br />
    <%= f.number_field :device_id %>
  </div>
  <div class="actions">
    <%= f.submit "Confirm Return", :class => "btn btn-primary" %>
  </div>
<% end %>

app/views/rentals/edit.html.erb
<div class="container">
	<div class="row">
<h1>Editing rental</h1>

<%= render 'form' %>

<%= link_to 'Show', @rental %> |
<%= link_to 'Back', rentals_path %>
</div>
</div>

app/views/rentals/index.html.erb
<div class="container">
  <div class="row">
<h1>Listing rentals</h1>
<table class="table table-condensed">
  <tr>
    <th>Name</th>
    <th>Email</th>
    <th>End</th>
    <th>Device</th>
    <th>Project</th>
    <th>Comments</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @rentals.each do |rental| %>
  <tr>
    <td><%= rental.renter %></td>
    <td><%= mail_to rental.email %></td>
    <td><%= rental.end %></td>
    <td><%= rental.device_id %></td>
    <td><%= rental.project %></td>
    <td><%= rental.comment %></td>
    <td><%= link_to 'Show', rental %></td>
    <td><%= link_to 'Edit', edit_rental_path(rental) %></td>
    <td><%= link_to 'Destroy', rental, method: :delete, data: { confirm: 'Are you sure?' }, :class => 'btn btn-default' %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Rental', new_rental_path, :class => "btn btn-primary" %>
</div>
</div>

app/views/rentals/new.html.erb
<div class="container">
	<div class="row">
		<div class="col-md-3">
			<h1>New rental</h1>
			<%= render 'form' %>
		</div>
	</div>
</div>

app/views/rentals/return.html.erb
<div class="container">
	<div class="row">
		<div class="col-md-12">
			<h1>Return rental</h1>
			<%= render 'returnForm' %>
		</div>
	</div>
</div>

app/views/rentals/show.html.erb
<div class="container">
	<div class="row">
<p id="notice"><%= notice %></p>
<p>
  <b>Name:</b>
  <%= @rental.renter %>
</p>
<p>
  <b>Email:</b>
  <%= @rental.email %>
</p>

<p>
  <b>End:</b>
  <%= @rental.end %>
</p>

<p>
  <b>Device:</b>
  <%= @rental.device_id %>
</p>



<%= link_to 'Back to Devices', devices_path, :class => "btn btn-info" %>
</div>
</div>